name: moto_365
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.11
  share: ^2.0.4
  # bugsnag_crashlytics: ^0.0.7
  pin_code_fields: ^6.1.0
  intl: ^0.17.0
  carousel_pro: ^1.0.0
  # chewie_audio: ^1.2.0
  image_picker: ^0.8.4+4
  location: ^4.3.0
  flutter_map: ^0.14.0
  geolocator: ^8.0.1
  latlong: ^0.6.1
  flutter_launcher_icons: ^0.9.2
  pdf: ^3.6.5
  searchable_dropdown: ^1.1.3
  geocoder: ^0.2.1
  file_picker: ^4.2.8
  youtube_player_flutter: ^8.0.0
  #flutter_mapbox_navigation: ^0.0.24
  font_awesome_flutter: ^9.2.0
  outline_material_icons: ^0.1.1
  video_player: ^2.2.7
  # shimmer: ^1.1.1
  flutter_spinkit: ^5.1.0
  # geolocator: ^8.0.1
  screen: ^0.0.5
  #notifications: ^0.0.3
  cloud_firestore: ^3.1.5
  # flutter_tagging: ^3.0.0
  # flutter_credit_card: ^0.1.3
  dropdown_search: ^2.0.1
  # html_editor: ^1.0.1
  flutter_html: ^2.2.1
  # #flutter_svg: ^0.19.0
  web_socket_channel: ^2.1.0
  url_launcher: ^6.0.17
  animations: ^2.0.2
  flutter_staggered_animations: ^1.0.0
  google_maps_flutter: ^2.1.1
  razorpay_flutter: ^1.2.7
  path_provider: ^2.0.8
  flutter_barcode_scanner: ^2.0.0
  #flutter_blue: ^0.8.0
  flutter_bluetooth_serial: ^0.4.0
  scoped_model: ^1.1.0
  percent_indicator: ^3.4.0
  flutter_mobile_vision_2: ^0.1.9
  camera: ^0.9.4+6
  image_cropper: ^1.4.1
  
  
  
 
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  #printing: ^5.6.0
  # flutter_mapbox_navigation: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logonew.png"  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.png
    - assets/images/hex.png
    - assets/images/vector.png
    - assets/images/slice.png
    - assets/images/right.png
    - assets/images/left.png
    - assets/images/logo.png
    - assets/images/logonew.png
    - assets/images/sleft.png
    - assets/images/sright.png
    - assets/images/Union.png
    - assets/images/Vectorcam.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/newhex.png
    - assets/images/onboarding3.png
    - assets/images/onboarding4.png
    - assets/images/uploadjson.png
    - assets/images/insurance1.png
    - assets/images/insurance2.png
    - assets/images/insurance3.png
    - assets/images/insurance4.png
    - assets/images/types/
    - assets/map_style.txt
    - assets/images/battery 1.png
    - assets/images/tyrehome.png
    - assets/fonts/Montserrat-Regular.ttf
    - assets/images/evform.png
    - assets/images/evform2.png
    - assets/images/evform3.png
    - assets/images/insurance.png
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 600
    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          style: italic
            
    - family: Praktika
      fonts:
        - asset: assets/fonts/Praktika-Light.ttf
    
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
